version: "3.5"

networks:
  radix-job-example:
    name: radix-image-builder-example

services:
  frontend:
    build:
      context: frontend
    image: radix-job-example-frontend
    container_name: radix-image-builder-example-frontend_container
    networks:
      - radix-job-example
    ports:
      - "8001:8001" # For local debug only; not exposed in prod
    volumes:
      - type: bind
        source: .
        target: /app

  auth-state:
    image: redis:5-alpine
    container_name: radix-image-builder-example-state_container
    networks:
      - radix-job-example
    ports:
      - "6379:6379"

  auth:
    image: quay.io/pusher/oauth2_proxy:v6.1.1
    container_name: radix-image-builder-example-auth_container
    environment:
      - OAUTH2_PROXY_PROVIDER=oidc # https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-protocols-oidc
      - OAUTH2_PROXY_OIDC_ISSUER_URL=https://login.microsoftonline.com/3aa4a235-b6e2-48d5-9195-7fcf05b459b0/v2.0
      - OAUTH2_PROXY_CLIENT_ID=${OAUTH2_PROXY_CLIENT_ID}
      - OAUTH2_PROXY_CLIENT_SECRET=${OAUTH2_PROXY_CLIENT_SECRET}
      - OAUTH2_PROXY_COOKIE_SECRET=${OAUTH2_PROXY_COOKIE_SECRET}
#      - OAUTH2_PROXY_SCOPE=openid email offline_access ${API_RESOURCE_ID}/user_impersonation # resource client id
      - OAUTH2_PROXY_REDIRECT_URL=http://localhost:8008/oauth2/callback
      - OAUTH2_PROXY_HTTP_ADDRESS=http://:8008
      - OAUTH2_PROXY_UPSTREAMS=http://frontend:8001
      - OAUTH2_PROXY_COOKIE_REFRESH=60m
      - OAUTH2_PROXY_REDIS_CONNECTION_URL=redis://auth-state:6379 # Where to store session info (the auth-state component)
      - OAUTH2_PROXY_SESSION_STORE_TYPE=redis # We're using Redis for storing session info instead of cookies (cookies would get too big for Edge and Safari)
      - OAUTH2_PROXY_COOKIE_SECURE=false # only for development
      - OAUTH2_PROXY_EMAIL_DOMAINS=*
      - OAUTH2_PROXY_PASS_ACCESS_TOKEN=true
      - OAUTH2_PROXY_PASS_USER_HEADERS=false
      - OAUTH2_PROXY_SKIP_PROVIDER_BUTTON=true
    networks:
      - radix-job-example
    ports:
      - "8008:8008" # In prod, this is served on port 443